#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compare AFSIM blue replay trace with reference TSPI CSV exports."""

import argparse
import csv
import math
from pathlib import Path

import numpy as np

EARTH_R = 6378137.0


def latlon_to_enu(lat_deg, lon_deg, lat0_deg, lon0_deg):
    lat = math.radians(lat_deg)
    lon = math.radians(lon_deg)
    lat0 = math.radians(lat0_deg)
    lon0 = math.radians(lon0_deg)
    x_e = (lon - lon0) * math.cos(0.5 * (lat + lat0)) * EARTH_R
    y_n = (lat - lat0) * EARTH_R
    return x_e, y_n


def load_ref_csv(path):
    t, lat, lon, alt = [], [], [], []
    with open(path, "r", encoding="utf-8") as f:
        r = csv.DictReader(f)
        for row in r:
            t.append(float(row["time_s"]))
            lat.append(float(row["lat_deg"]))
            lon.append(float(row["lon_deg"]))
            alt.append(float(row["alt_m"]))
    return np.array(t), np.array(lat), np.array(lon), np.array(alt)


def load_trace(path, platform):
    t, lat, lon, alt = [], [], [], []
    with open(path, "r", encoding="utf-8") as f:
        r = csv.DictReader(f)
        for row in r:
            if row["platform"] != platform:
                continue
            t.append(float(row["time_s"]))
            lat.append(float(row["lat_deg"]))
            lon.append(float(row["lon_deg"]))
            alt.append(float(row["alt_m"]))
    return np.array(t), np.array(lat), np.array(lon), np.array(alt)


def interp_ref(t_ref, arr_ref, t_q):
    return np.interp(t_q, t_ref, arr_ref)


def compute_position_errors(t_ref, lat_ref, lon_ref, alt_ref, t_obs, lat_obs, lon_obs, alt_obs):
    if len(t_obs) == 0:
        return np.array([])
    lat_ref_i = interp_ref(t_ref, lat_ref, t_obs)
    lon_ref_i = interp_ref(t_ref, lon_ref, t_obs)
    alt_ref_i = interp_ref(t_ref, alt_ref, t_obs)

    lat0 = float(lat_ref_i[0])
    lon0 = float(lon_ref_i[0])
    errs = np.zeros(len(t_obs), dtype=np.float64)
    for i in range(len(t_obs)):
        xr, yr = latlon_to_enu(lat_ref_i[i], lon_ref_i[i], lat0, lon0)
        xo, yo = latlon_to_enu(lat_obs[i], lon_obs[i], lat0, lon0)
        dz = alt_obs[i] - alt_ref_i[i]
        errs[i] = math.sqrt((xo - xr) ** 2 + (yo - yr) ** 2 + dz ** 2)
    return errs


def summarize(name, errs, threshold):
    if errs.size == 0:
        return {"name": name, "n": 0, "mean": None, "max": None, "p95": None, "pass": False}
    return {
        "name": name,
        "n": int(errs.size),
        "mean": float(np.mean(errs)),
        "max": float(np.max(errs)),
        "p95": float(np.percentile(errs, 95)),
        "pass": bool(np.max(errs) < threshold),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trace", required=True, help="output/blue_replay_trace.csv generated by scenario")
    ap.add_argument("--ref_blue_1", required=True, help="replay/tspi_blue_1.csv")
    ap.add_argument("--ref_blue_2", required=True, help="replay/tspi_blue_2.csv")
    ap.add_argument("--threshold_m", type=float, default=20.0)
    args = ap.parse_args()

    t1r, lat1r, lon1r, alt1r = load_ref_csv(Path(args.ref_blue_1))
    t2r, lat2r, lon2r, alt2r = load_ref_csv(Path(args.ref_blue_2))
    t1o, lat1o, lon1o, alt1o = load_trace(Path(args.trace), "blue_1")
    t2o, lat2o, lon2o, alt2o = load_trace(Path(args.trace), "blue_2")

    e1 = compute_position_errors(t1r, lat1r, lon1r, alt1r, t1o, lat1o, lon1o, alt1o)
    e2 = compute_position_errors(t2r, lat2r, lon2r, alt2r, t2o, lat2o, lon2o, alt2o)
    s1 = summarize("blue_1", e1, args.threshold_m)
    s2 = summarize("blue_2", e2, args.threshold_m)

    for s in (s1, s2):
        if s["n"] == 0:
            print(f"[FAIL] {s['name']}: no samples in trace")
            continue
        status = "PASS" if s["pass"] else "FAIL"
        print(
            f"[{status}] {s['name']}: n={s['n']} mean={s['mean']:.3f}m "
            f"p95={s['p95']:.3f}m max={s['max']:.3f}m threshold={args.threshold_m:.3f}m"
        )

    if s1["pass"] and s2["pass"]:
        print("[PASS] Blue replay trajectory validation passed.")
    else:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
